%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\mperr\Documents\MATLAB\RHEOL_GUI-1.0\CRM_slab_format.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-Jul-2023 14:36:41

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A5:L85";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "DEPTH", "VarName4", "VarName5", "Mineral", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["categorical", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName5"], "EmptyFieldRule", "auto");

% Import the data
CRMslabformat = readtable("C:\Users\mperr\Documents\MATLAB\RHEOL_GUI-1.0\CRM_slab_format.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts